---
apiVersion: v1
kind: Service
metadata:
  name: my-application-service
spec:
  selector:
    app: my-application
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-application
  name: my-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-application
  template:
    metadata: 
      labels: 
        app: my-application
    spec:
      containers:
      - name: frontend-python
        image: index.docker.io/tadeuuuuu/my-images-2020:frontend-teste-2.0
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 8000
      - name: backend-go
        image: index.docker.io/tadeuuuuu/my-images-2020:backend-teste-1.0
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred 
